name: TestPlugin
version: 1.3.1
main: me.mackaroni.testplugin.TestPlugin
author: mack-aroni
description: Test Plugin
api-version: "1.20"

commands:
  feed:
    description: Replenish player hunger
    usage: /feed
  gamble:
    description: Gamble with tokens for rewards
    usage: /gamble